name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Create JWT keys
        run: |
          mkdir -p src/main/resources/certs

          echo "${{ secrets.JWT_PUBLIC_KEY }}" > src/main/resources/certs/public.pem

          echo "${{ secrets.JWT_PRIVATE_KEY }}" > src/main/resources/certs/private.pem

      - name: Build
        run: ./mvnw verify